### ISSUE TITLE
Missing bounds checks on input array lengths

### ISSUE THREAD

**Issue by sfackler** [stainless-steel/lapack#15]
For example, dsgesv must have `a.len() >= lda * n`. These checks either need to be added to the wrapper functions or they should be marked unsafe.

**Comment by IvanUkhov** [comment]
Related to [blas/#18](https://github.com/stainless-steel/blas/issues/18). Again, if anybody knows an automated way of doing this, please share. Thanks.

**Comment by IvanUkhov** [comment]
Adding checks is unrealistic in my opinion. There’re too many functions with too many arguments. One would have to consider each function separately, reading carefully the documentation and deciding if any checks should be added on a case-by-case basis. It’s no scalable and error-prone.

It seems to me that the right thing to do is indeed to mark everything unsafe, as @sfackler suggested. Pretty much every function in both `blas` and `lapack` takes a number of integers that tell the underlying implementation the size of the input/output arrays. It’s very easy to mess up the memory by passing a wrong value, and the current function signatures tell nothing about this danger.

@bluss, @cmr: What do you think about marking the functions in `blas` and `lapack` unsafe?

**Comment by bluss** [comment]
I haven't used the functions in blas, only using the ffi functions which are already unsafe. The reason is among other things, that the slice-based API is not expressive enough, it's not a good fit for data described by a pointer + strides per axis.

I think they should be unsafe if they are and, they are :smile:

They are unsafe in the pattern that is common: Some combinations of parameters are invalid and cause violation of memory safety rules, and the caller needs to ensure the used combination is valid.

**Comment by IvanUkhov** [comment]
Fixed in #18.
