### ISSUE TITLE
lwork parameter for dgesvd() should be a signed integer [regression]

### ISSUE THREAD

**Issue by astraw** [stainless-steel/lapack#4]
Here's a regression with introduced by the new wrappers of 0.4: lwork for dgesvd() now wrongly takes a type of usize (previously it was i32). As shown in [the upstream documentation](http://www.netlib.org/lapack/explore-html/d8/d2d/dgesvd_8f.html), lwork should be a signed integer. This is important because setting it to -1 is useful for querying the optimal size of the work array.

The old tests would have caught this. Why were they removed? I think they should be brought back, perhaps as doctest examples.

**Comment by astraw** [comment]
Hmm, I see back in 0.3.4 the lwork parameter had type usize. So I was wrong the report above -- this is not a regression but rather for some reason things were not broken for me previously and now are broking (likely due to me using rust nightly which is now correctly catching the error). Apologies. Still, we should fix this and get the tests running again, too.

I'll dig in a little more...

**Comment by IvanUkhov** [comment]
Done. Please give a try to v0.5.0.

I recently added all the missing routines with respect to the reference implementation by Netlib (LAPACK v3.5.0), and now the package is complete, but some things still need some polishing since it was done in an [automated fashion](https://github.com/stainless-steel/lapack/blob/master/generate.py). If you notice any other inconsistency, please let me know. Thanks a lot for the help!


Regards,
Ivan
